
        function randomNum() {
          var x = Math.floor(Math.random()* 999999999999999999) + 100000000000000000;
        }
        randomNum();
        document.write("<p>YOU ARE IN VIOLATION OF DIGITAL LAW. A.I. TECHNOLOGY HAS IDENTIFIED YOU AS USER_"+x+" THROUGH VIDEO SURVEILLANCE. WE HAVE AN OUTSTANDING WARRANT FOR YOUR ARREST. STAY WHERE YOU ARE UNTIL WE ARRIVE. DO NOT RESIST.</p>");
